version: "3.9"

services:

    db:
        image: postgres:14.0-alpine3.14
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}

    #backend:
        
    
    #frontend:


volumes:
    postgres_data: