version: "3.9"

services:
  database:
    image: postgres:14.0-alpine3.14
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: bitnami/redis:6.2
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
    networks:
      - backend

  api:
    image: area/backend
    build: backend
    environment:
      - API_HOST=0.0.0.0
      - API_PORT
      - API_SESSION_SECRET
      - DB_HOST=database
      - DB_PORT
      - DB_URL=postgresql://$DB_USER:$DB_PASS@database:$DB_PORT/$DB_NAME
      - REDIS_PASS
      - REDIS_HOST=redis
      - REDIS_PORT
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - backend
    depends_on:
      - database
      - redis



  #frontend:

networks:
  backend:

volumes:
  postgres_data:
