version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "22181:22181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 22181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "19092:19092"
      - "19091:19091"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
    depends_on:
      - zookeeper
    
  kafka-gui:
    container_name: kafka-gui
    image: sheepkiller/kafka-manager:latest
    ports:
      - "9000:9000"
    environment:
      - "ZK_HOSTS=${IP}:22181"
      - "APPLICATION_SECRET=letmein"
      - "KM_ARGS=-Djava.net.preferIPv4Stack=true"
    depends_on:
      - kafka

  redis:
    image: bitnami/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - "${REDIS_PORT}:6379"