version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "22181:22181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 22181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "19092:19092"
      - "19091:19091"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:22181
      KAFKA_LISTENERS: LISTENER_INTERNAL://kafka:19092,LISTENER_EXTERNAL://kafka:19091
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka:19092,LISTENER_EXTERNAL://localhost:19091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
    depends_on:
      - zookeeper
    
  kafka-gui:
    container_name: kafka-gui
    image: sheepkiller/kafka-manager:latest
    ports:
      - "9000:9000"
    environment:
      - "ZK_HOSTS=${IP}:22181"
      - "APPLICATION_SECRET=letmein"
      - "KM_ARGS=-Djava.net.preferIPv4Stack=true"
    depends_on:
      - kafka

  redis:
    image: bitnami/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - "${REDIS_PORT}:6379"