name: Continuous Integration Backend

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: self-hosted
    env:
      DB_PORT: 5432
      DB_USER: root
      DB_PASS: mypassword
      DB_NAME: area
      DB_USER_SCHEMA: user
      DB_WORKFLOW_SCHEMA: workflow
      DB_CREDENTIAL_SCHEMA: credential
      REDIS_PORT: 6379
      REDIS_PASS: pass
      API_HOST: localhost
      USER_API_PORT: 5000
      USER_API_SESSION_SECRET: secret
      USER_API_SESSION_MAX_AGE: 2160000
      USER_API_SESSION_SECURE: false
      WORKFLOW_API_PORT: 8000
      CREDENTIAL_API_PORT: 8001
      GRPC_DOC_PORT: 9000
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Compose
        run: docker compose up -d

      - name: Wait for User API
        run: |
          API_PORT=$USER_API_PORT ./backend/util/wait-for-api.sh

      - name: Run Postman suite for userAPI
        uses: matt-ball/newman-action@master
        with:
          collection: backend/userAPI/test/postman/User-API-collection.json
          environment: backend/userAPI/test/postman/Area-environment.json

      - name: Run Postman suite for workflow API gateway
        uses: matt-ball/newman-action@master
        with:
          collection: backend/userAPI/test/postman/Workflow-gateway-collection.json
          environment: backend/userAPI/test/postman/Area-environment.json

      - name: Run Postman suite for task API gateway
        uses: matt-ball/newman-action@master
        with:
          collection: backend/userAPI/test/postman/Task-gateway-collection.json
          environment: backend/userAPI/test/postman/Area-environment.json

      - name: Down docker
        run: docker compose stop
