name: Continuous Integration Backend

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DB_PORT: 5432
      DB_USER: root
      DB_PASS: mypassword
      DB_NAME: area
      REDIS_PORT: 6379
      REDIS_PASS: pass
      API_PORT: 5000

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Compose
        run: docker compose up -d

      - name: Run Postman suite
        uses: matt-ball/newman-action@master
        with:
          collection: backend/test/postman/User-API-collection.json
          environment: backend/test/postman/Area-environment.json

      - name: Down docker
        run: docker compose stop
