name: Build Area

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]

defaults:
    run:
        shell: bash

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
              os: [ubuntu-latest, macos-latest]
              build_type: [Debug, Release]

        name: Build Area
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2

            - name: Install Docker on Macos
              if: ${{ matrix.os == 'macos-latest' }}
              run: |
                mkdir -p ~/.docker/machine/cache
                curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
                brew install docker docker-machine

            - name: Build Docker Compose
              run: docker compose build
