name: Build Area

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_type: [Debug, Release]

    name: Build Area
    runs-on: ${{ matrix.os }}
    env:
      DB_PORT: 5432
      DB_USER: root
      DB_PASS: mypassword
      DB_NAME: area
      REDIS_PORT: 6379
      REDIS_PASS: pass
      API_PORT: 5000
      API_SESSION_SECRET: secret

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Compose
        run: docker compose build
