name: Build Area

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    name: Build Area
    runs-on: ubuntu-latest
    env:
      DB_PORT: 5432
      DB_USER: root
      DB_PASS: mypassword
      DB_NAME: area
      DB_USER_SCHEMA: user
      DB_WORKFLOW_SCHEMA: workflow
      REDIS_PORT: 6379
      REDIS_PASS: pass
      USER_API_PORT: 5000
      USER_API_SESSION_SECRET: secret
      USER_API_SESSION_MAX_AGE: 2160000
      USER_API_SESSION_SECURE: false
      WORKFLOW_API_PORT: 8000
      GRPC_DOC_PORT: 9000
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Compose
        run: docker compose build
