name: Build Area

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]

defaults:
    run:
        shell: bash

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
              os: [ubuntu-latest, windows-latest]
              build_type: [Debug, Release]

        name: Build Area
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - name: Build Docker Compose
              run: docker compose build
