name: Build Area

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Compose
        run: docker compose build client_mobile

      - uses: actions/upload-artifact@v3
        with:
          name: area
          path: app-release.apk